name: pdf_flutter
description: Displaying PDF from Network, File and assets easily like we display Image in Flutter Widget.
version: 1.1.3
homepage: https://github.com/erluxman/pdf_flutter

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  pedantic: ^1.9.2
  path_provider: ^1.6.24
  flutter_cache_manager: ^2.0.0
  http: ^0.12.2
  uuid: ^2.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.erluxman.pdf_flutter
        pluginClass: PdfFlutterPlugin
      ios:
        pluginClass: PdfFlutterPlugin